{
    "env": { "es6": true, "browser": true, "node": true },
    "extends":
        [
            "eslint:recommended",
            "prettier",
            "plugin:@typescript-eslint/recommended",
        ],
    "plugins": ["prettier", "@typescript-eslint"],
    parser: "@typescript-eslint/parser",
    "parserOptions": { "ecmaVersion": 2020, "sourceType": "module" },
    "rules":
        {
            "prettier/prettier": "error",
            "camelcase": ["error"],
            "eqeqeq": ["error", "always"],
        },
}
