{
    "env": { "es6": true, "browser": true, "node": true },
    "extends": ["eslint:recommended", "prettier"],
    "plugins": ["prettier"],
    "parserOptions": { "ecmaVersion": 2020, "sourceType": "module" },
    "rules":
        {
            "prettier/prettier": "error",
            "camelcase": ["error"],
            "eqeqeq": ["error", "always"],
        },
}
