{
    "plugins": ["stylelint-prettier"],
    "rules": { "indentation": 4, "no-descending-specificity": null },
    extends:
        [
            "stylelint-config-standard",
            "stylelint-config-prettier",
            "stylelint-prettier/recommended",
            "stylelint-config-standard-scss",
        ],
}
